/* -------------------------------------------------------------------------
 *  This file is part of the oGRAC project.
 * Copyright (c) 2024 Huawei Technologies Co.,Ltd.
 *
 * oGRAC is licensed under Mulan PSL v2.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *
 *          http://license.coscl.org.cn/MulanPSL2
 *
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 * -------------------------------------------------------------------------
 *
 * var_cmp.c
 *
 *
 * IDENTIFICATION
 * src/common/variant/var_cmp.c
 *
 * -------------------------------------------------------------------------
 */
#include "var_cmp.h"
#include "var_opr.h"
#include "var_defs.h"

#define __CMP_TYPE_DEF(lt, rt, rst, st, compat) \
    [OG_TYPE_I((lt))][OG_TYPE_I((rt))] = {.cmp_type = (rst), .same_type = (st), .compatible = (compat)}

cmp_rule_t g_cmp_rules[VAR_TYPE_ARRAY_SIZE][VAR_TYPE_ARRAY_SIZE] = {
    __CMP_TYPE_DEF(OG_TYPE_UINT32, OG_TYPE_UINT32,  OG_TYPE_UINT32, OG_TRUE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_UINT32, OG_TYPE_INTEGER,  OG_TYPE_BIGINT, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_UINT32, OG_TYPE_BIGINT,   OG_TYPE_BIGINT, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_UINT32, OG_TYPE_REAL,     OG_TYPE_REAL, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_UINT32, OG_TYPE_NUMBER,   OG_TYPE_NUMBER, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_UINT32, OG_TYPE_NUMBER2,   OG_TYPE_NUMBER2, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_UINT32, OG_TYPE_DECIMAL,  OG_TYPE_NUMBER, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_UINT32, OG_TYPE_CHAR,     OG_TYPE_NUMBER, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_UINT32, OG_TYPE_VARCHAR,  OG_TYPE_NUMBER, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_UINT32, OG_TYPE_STRING,   OG_TYPE_NUMBER, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_UINT32, OG_TYPE_BOOLEAN,  OG_TYPE_INTEGER, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_UINT32, OG_TYPE_BINARY,     OG_TYPE_NUMBER, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_UINT32, OG_TYPE_VARBINARY,  OG_TYPE_NUMBER, OG_FALSE, OG_TRUE),

    __CMP_TYPE_DEF(OG_TYPE_INTEGER, OG_TYPE_UINT32,   OG_TYPE_BIGINT, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_INTEGER, OG_TYPE_INTEGER,  OG_TYPE_INTEGER, OG_TRUE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_INTEGER, OG_TYPE_BIGINT,   OG_TYPE_BIGINT, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_INTEGER, OG_TYPE_REAL,     OG_TYPE_REAL, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_INTEGER, OG_TYPE_NUMBER,   OG_TYPE_NUMBER, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_INTEGER, OG_TYPE_NUMBER2,   OG_TYPE_NUMBER2, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_INTEGER, OG_TYPE_DECIMAL,  OG_TYPE_NUMBER, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_INTEGER, OG_TYPE_CHAR,     OG_TYPE_NUMBER, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_INTEGER, OG_TYPE_VARCHAR,  OG_TYPE_NUMBER, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_INTEGER, OG_TYPE_STRING,   OG_TYPE_NUMBER, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_INTEGER, OG_TYPE_BOOLEAN,  OG_TYPE_INTEGER, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_INTEGER, OG_TYPE_BINARY,     OG_TYPE_NUMBER, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_INTEGER, OG_TYPE_VARBINARY,  OG_TYPE_NUMBER, OG_FALSE, OG_TRUE),

    __CMP_TYPE_DEF(OG_TYPE_BIGINT, OG_TYPE_UINT32, OG_TYPE_BIGINT, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_BIGINT, OG_TYPE_INTEGER, OG_TYPE_BIGINT, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_BIGINT, OG_TYPE_BIGINT, OG_TYPE_BIGINT, OG_TRUE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_BIGINT, OG_TYPE_REAL, OG_TYPE_REAL, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_BIGINT, OG_TYPE_NUMBER, OG_TYPE_NUMBER, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_BIGINT, OG_TYPE_NUMBER2, OG_TYPE_NUMBER2, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_BIGINT, OG_TYPE_DECIMAL, OG_TYPE_NUMBER, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_BIGINT, OG_TYPE_CHAR, OG_TYPE_NUMBER, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_BIGINT, OG_TYPE_VARCHAR, OG_TYPE_NUMBER, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_BIGINT, OG_TYPE_STRING, OG_TYPE_NUMBER, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_BIGINT, OG_TYPE_BOOLEAN, OG_TYPE_BIGINT, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_BIGINT, OG_TYPE_BINARY, OG_TYPE_NUMBER, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_BIGINT, OG_TYPE_VARBINARY, OG_TYPE_NUMBER, OG_FALSE, OG_TRUE),

    __CMP_TYPE_DEF(OG_TYPE_UINT64, OG_TYPE_UINT64, OG_TYPE_UINT64, OG_TRUE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_UINT64, OG_TYPE_UINT32, OG_TYPE_UINT64, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_UINT64, OG_TYPE_INTEGER, OG_TYPE_NUMBER, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_UINT64, OG_TYPE_BIGINT, OG_TYPE_NUMBER, OG_FALSE, OG_TRUE),

    __CMP_TYPE_DEF(OG_TYPE_REAL, OG_TYPE_UINT32, OG_TYPE_REAL, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_REAL, OG_TYPE_INTEGER, OG_TYPE_REAL, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_REAL, OG_TYPE_BIGINT, OG_TYPE_REAL, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_REAL, OG_TYPE_REAL, OG_TYPE_REAL, OG_TRUE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_REAL, OG_TYPE_NUMBER, OG_TYPE_REAL, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_REAL, OG_TYPE_NUMBER2, OG_TYPE_REAL, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_REAL, OG_TYPE_DECIMAL, OG_TYPE_REAL, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_REAL, OG_TYPE_BOOLEAN, OG_TYPE_REAL, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_REAL, OG_TYPE_CHAR, OG_TYPE_NUMBER, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_REAL, OG_TYPE_VARCHAR, OG_TYPE_NUMBER, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_REAL, OG_TYPE_STRING, OG_TYPE_NUMBER, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_REAL, OG_TYPE_BINARY, OG_TYPE_NUMBER, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_REAL, OG_TYPE_VARBINARY, OG_TYPE_NUMBER, OG_FALSE, OG_TRUE),

    __CMP_TYPE_DEF(OG_TYPE_NUMBER, OG_TYPE_UINT32, OG_TYPE_NUMBER, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_NUMBER, OG_TYPE_INTEGER, OG_TYPE_NUMBER, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_NUMBER, OG_TYPE_BIGINT, OG_TYPE_NUMBER, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_NUMBER, OG_TYPE_REAL, OG_TYPE_REAL, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_NUMBER, OG_TYPE_NUMBER, OG_TYPE_NUMBER, OG_TRUE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_NUMBER, OG_TYPE_NUMBER2, OG_TYPE_NUMBER2, OG_TRUE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_NUMBER, OG_TYPE_DECIMAL, OG_TYPE_NUMBER, OG_TRUE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_NUMBER, OG_TYPE_BOOLEAN, OG_TYPE_NUMBER, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_NUMBER, OG_TYPE_CHAR, OG_TYPE_NUMBER, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_NUMBER, OG_TYPE_VARCHAR, OG_TYPE_NUMBER, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_NUMBER, OG_TYPE_STRING, OG_TYPE_NUMBER, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_NUMBER, OG_TYPE_BINARY, OG_TYPE_NUMBER, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_NUMBER, OG_TYPE_VARBINARY, OG_TYPE_NUMBER, OG_FALSE, OG_TRUE),

    __CMP_TYPE_DEF(OG_TYPE_NUMBER2, OG_TYPE_UINT32, OG_TYPE_NUMBER2, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_NUMBER2, OG_TYPE_INTEGER, OG_TYPE_NUMBER2, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_NUMBER2, OG_TYPE_BIGINT, OG_TYPE_NUMBER2, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_NUMBER2, OG_TYPE_REAL, OG_TYPE_REAL, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_NUMBER2, OG_TYPE_NUMBER, OG_TYPE_NUMBER2, OG_TRUE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_NUMBER2, OG_TYPE_NUMBER2, OG_TYPE_NUMBER2, OG_TRUE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_NUMBER2, OG_TYPE_DECIMAL, OG_TYPE_NUMBER2, OG_TRUE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_NUMBER2, OG_TYPE_BOOLEAN, OG_TYPE_NUMBER2, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_NUMBER2, OG_TYPE_CHAR, OG_TYPE_NUMBER2, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_NUMBER2, OG_TYPE_VARCHAR, OG_TYPE_NUMBER2, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_NUMBER2, OG_TYPE_STRING, OG_TYPE_NUMBER2, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_NUMBER2, OG_TYPE_BINARY, OG_TYPE_NUMBER2, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_NUMBER2, OG_TYPE_VARBINARY, OG_TYPE_NUMBER2, OG_FALSE, OG_TRUE),

    __CMP_TYPE_DEF(OG_TYPE_DECIMAL, OG_TYPE_UINT32, OG_TYPE_NUMBER, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_DECIMAL, OG_TYPE_INTEGER, OG_TYPE_NUMBER, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_DECIMAL, OG_TYPE_BIGINT, OG_TYPE_NUMBER, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_DECIMAL, OG_TYPE_REAL, OG_TYPE_REAL, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_DECIMAL, OG_TYPE_NUMBER, OG_TYPE_NUMBER, OG_TRUE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_DECIMAL, OG_TYPE_NUMBER2, OG_TYPE_NUMBER2, OG_TRUE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_DECIMAL, OG_TYPE_DECIMAL, OG_TYPE_NUMBER, OG_TRUE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_DECIMAL, OG_TYPE_BOOLEAN, OG_TYPE_DECIMAL, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_DECIMAL, OG_TYPE_CHAR, OG_TYPE_NUMBER, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_DECIMAL, OG_TYPE_VARCHAR, OG_TYPE_NUMBER, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_DECIMAL, OG_TYPE_STRING, OG_TYPE_NUMBER, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_DECIMAL, OG_TYPE_BINARY, OG_TYPE_NUMBER, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_DECIMAL, OG_TYPE_VARBINARY, OG_TYPE_NUMBER, OG_FALSE, OG_TRUE),

    // BINARY not support bool yet
    __CMP_TYPE_DEF(OG_TYPE_BOOLEAN, OG_TYPE_UINT32, OG_TYPE_UINT32, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_BOOLEAN, OG_TYPE_INTEGER, OG_TYPE_INTEGER, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_BOOLEAN, OG_TYPE_BIGINT, OG_TYPE_BIGINT, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_BOOLEAN, OG_TYPE_REAL, OG_TYPE_REAL, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_BOOLEAN, OG_TYPE_NUMBER, OG_TYPE_NUMBER, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_BOOLEAN, OG_TYPE_NUMBER2, OG_TYPE_NUMBER2, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_BOOLEAN, OG_TYPE_DECIMAL, OG_TYPE_DECIMAL, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_BOOLEAN, OG_TYPE_CHAR, OG_TYPE_BOOLEAN, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_BOOLEAN, OG_TYPE_VARCHAR, OG_TYPE_BOOLEAN, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_BOOLEAN, OG_TYPE_STRING, OG_TYPE_BOOLEAN, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_BOOLEAN, OG_TYPE_BOOLEAN, OG_TYPE_BOOLEAN, OG_TRUE, OG_TRUE),

    __CMP_TYPE_DEF(OG_TYPE_CHAR, OG_TYPE_UINT32, OG_TYPE_NUMBER, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_CHAR, OG_TYPE_INTEGER, OG_TYPE_NUMBER, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_CHAR, OG_TYPE_BIGINT, OG_TYPE_NUMBER, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_CHAR, OG_TYPE_REAL, OG_TYPE_NUMBER, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_CHAR, OG_TYPE_NUMBER, OG_TYPE_NUMBER, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_CHAR, OG_TYPE_NUMBER2, OG_TYPE_NUMBER2, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_CHAR, OG_TYPE_DECIMAL, OG_TYPE_NUMBER, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_CHAR, OG_TYPE_CHAR, OG_TYPE_CHAR, OG_TRUE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_CHAR, OG_TYPE_VARCHAR, OG_TYPE_STRING, OG_TRUE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_CHAR, OG_TYPE_STRING, OG_TYPE_STRING, OG_TRUE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_CHAR, OG_TYPE_BINARY, OG_TYPE_BINARY, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_CHAR, OG_TYPE_VARBINARY, OG_TYPE_VARBINARY, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_CHAR, OG_TYPE_RAW, OG_TYPE_STRING, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_CHAR, OG_TYPE_DATE, OG_TYPE_DATE, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_CHAR, OG_TYPE_TIMESTAMP, OG_TYPE_TIMESTAMP, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_CHAR, OG_TYPE_TIMESTAMP_TZ_FAKE, OG_TYPE_TIMESTAMP, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_CHAR, OG_TYPE_TIMESTAMP_TZ, OG_TYPE_TIMESTAMP_TZ, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_CHAR, OG_TYPE_TIMESTAMP_LTZ, OG_TYPE_TIMESTAMP_LTZ, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_CHAR, OG_TYPE_BOOLEAN, OG_TYPE_BOOLEAN, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_CHAR, OG_TYPE_INTERVAL_YM, OG_TYPE_INTERVAL_YM, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_CHAR, OG_TYPE_INTERVAL_DS, OG_TYPE_INTERVAL_DS, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_CHAR, OG_TYPE_ARRAY, OG_TYPE_ARRAY, OG_FALSE, OG_FALSE),

    __CMP_TYPE_DEF(OG_TYPE_VARCHAR, OG_TYPE_INTEGER, OG_TYPE_NUMBER, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_VARCHAR, OG_TYPE_BIGINT, OG_TYPE_NUMBER, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_VARCHAR, OG_TYPE_REAL, OG_TYPE_NUMBER, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_VARCHAR, OG_TYPE_NUMBER, OG_TYPE_NUMBER, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_VARCHAR, OG_TYPE_NUMBER2, OG_TYPE_NUMBER2, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_VARCHAR, OG_TYPE_DECIMAL, OG_TYPE_NUMBER, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_VARCHAR, OG_TYPE_CHAR, OG_TYPE_STRING, OG_TRUE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_VARCHAR, OG_TYPE_VARCHAR, OG_TYPE_STRING, OG_TRUE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_VARCHAR, OG_TYPE_STRING, OG_TYPE_STRING, OG_TRUE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_VARCHAR, OG_TYPE_BINARY, OG_TYPE_BINARY, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_VARCHAR, OG_TYPE_VARBINARY, OG_TYPE_VARBINARY, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_VARCHAR, OG_TYPE_RAW, OG_TYPE_VARCHAR, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_VARCHAR, OG_TYPE_DATE, OG_TYPE_DATE, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_VARCHAR, OG_TYPE_TIMESTAMP, OG_TYPE_TIMESTAMP, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_VARCHAR, OG_TYPE_TIMESTAMP_TZ_FAKE, OG_TYPE_TIMESTAMP, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_VARCHAR, OG_TYPE_TIMESTAMP_TZ, OG_TYPE_TIMESTAMP_TZ, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_VARCHAR, OG_TYPE_TIMESTAMP_LTZ, OG_TYPE_TIMESTAMP_LTZ, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_VARCHAR, OG_TYPE_BOOLEAN, OG_TYPE_BOOLEAN, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_VARCHAR, OG_TYPE_INTERVAL_YM, OG_TYPE_INTERVAL_YM, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_VARCHAR, OG_TYPE_INTERVAL_DS, OG_TYPE_INTERVAL_DS, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_VARCHAR, OG_TYPE_ARRAY, OG_TYPE_ARRAY, OG_FALSE, OG_FALSE),

    __CMP_TYPE_DEF(OG_TYPE_STRING, OG_TYPE_UINT32, OG_TYPE_NUMBER, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_STRING, OG_TYPE_INTEGER, OG_TYPE_NUMBER, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_STRING, OG_TYPE_BIGINT, OG_TYPE_NUMBER, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_STRING, OG_TYPE_REAL, OG_TYPE_NUMBER, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_STRING, OG_TYPE_NUMBER, OG_TYPE_NUMBER, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_STRING, OG_TYPE_NUMBER2, OG_TYPE_NUMBER2, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_STRING, OG_TYPE_DECIMAL, OG_TYPE_NUMBER, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_STRING, OG_TYPE_CHAR, OG_TYPE_STRING, OG_TRUE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_STRING, OG_TYPE_VARCHAR, OG_TYPE_STRING, OG_TRUE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_STRING, OG_TYPE_STRING, OG_TYPE_STRING, OG_TRUE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_STRING, OG_TYPE_BINARY, OG_TYPE_BINARY, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_STRING, OG_TYPE_VARBINARY, OG_TYPE_VARBINARY, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_STRING, OG_TYPE_RAW, OG_TYPE_STRING, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_STRING, OG_TYPE_DATE, OG_TYPE_DATE, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_STRING, OG_TYPE_TIMESTAMP, OG_TYPE_TIMESTAMP, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_STRING, OG_TYPE_TIMESTAMP_TZ_FAKE, OG_TYPE_TIMESTAMP, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_STRING, OG_TYPE_TIMESTAMP_TZ, OG_TYPE_TIMESTAMP_TZ, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_STRING, OG_TYPE_TIMESTAMP_LTZ, OG_TYPE_TIMESTAMP_LTZ, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_STRING, OG_TYPE_BOOLEAN, OG_TYPE_BOOLEAN, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_STRING, OG_TYPE_INTERVAL_YM, OG_TYPE_INTERVAL_YM, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_STRING, OG_TYPE_INTERVAL_DS, OG_TYPE_INTERVAL_DS, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_STRING, OG_TYPE_ARRAY, OG_TYPE_ARRAY, OG_FALSE, OG_FALSE),

    __CMP_TYPE_DEF(OG_TYPE_BINARY, OG_TYPE_CHAR, OG_TYPE_BINARY, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_BINARY, OG_TYPE_VARCHAR, OG_TYPE_BINARY, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_BINARY, OG_TYPE_STRING, OG_TYPE_BINARY, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_BINARY, OG_TYPE_BINARY, OG_TYPE_BINARY, OG_TRUE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_BINARY, OG_TYPE_VARBINARY, OG_TYPE_VARBINARY, OG_TRUE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_BINARY, OG_TYPE_RAW, OG_TYPE_BINARY, OG_FALSE, OG_TRUE),

    __CMP_TYPE_DEF(OG_TYPE_RAW, OG_TYPE_CHAR, OG_TYPE_STRING, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_RAW, OG_TYPE_VARCHAR, OG_TYPE_VARCHAR, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_RAW, OG_TYPE_STRING, OG_TYPE_STRING, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_RAW, OG_TYPE_RAW, OG_TYPE_RAW, OG_TRUE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_RAW, OG_TYPE_BINARY, OG_TYPE_BINARY, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_RAW, OG_TYPE_VARBINARY, OG_TYPE_VARBINARY, OG_FALSE, OG_TRUE),

    __CMP_TYPE_DEF(OG_TYPE_BLOB, OG_TYPE_CHAR, OG_TYPE_STRING, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_BLOB, OG_TYPE_VARCHAR, OG_TYPE_STRING, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_BLOB, OG_TYPE_STRING, OG_TYPE_STRING, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_BLOB, OG_TYPE_BINARY, OG_TYPE_VARBINARY, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_BLOB, OG_TYPE_RAW, OG_TYPE_RAW, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_BLOB, OG_TYPE_VARBINARY, OG_TYPE_VARBINARY, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_BLOB, OG_TYPE_BLOB, OG_TYPE_VARBINARY, OG_TRUE, OG_TRUE),

    __CMP_TYPE_DEF(OG_TYPE_CLOB, OG_TYPE_UINT32, OG_TYPE_NUMBER, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_CLOB, OG_TYPE_INTEGER, OG_TYPE_NUMBER, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_CLOB, OG_TYPE_BIGINT, OG_TYPE_NUMBER, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_CLOB, OG_TYPE_REAL, OG_TYPE_NUMBER, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_CLOB, OG_TYPE_NUMBER, OG_TYPE_NUMBER, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_CLOB, OG_TYPE_NUMBER2, OG_TYPE_NUMBER2, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_CLOB, OG_TYPE_DECIMAL, OG_TYPE_NUMBER, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_CLOB, OG_TYPE_CHAR, OG_TYPE_STRING, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_CLOB, OG_TYPE_VARCHAR, OG_TYPE_STRING, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_CLOB, OG_TYPE_STRING, OG_TYPE_STRING, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_CLOB, OG_TYPE_BINARY, OG_TYPE_BINARY, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_CLOB, OG_TYPE_VARBINARY, OG_TYPE_VARBINARY, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_CLOB, OG_TYPE_RAW, OG_TYPE_STRING, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_CLOB, OG_TYPE_DATE, OG_TYPE_DATE, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_CLOB, OG_TYPE_TIMESTAMP, OG_TYPE_TIMESTAMP, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_CLOB, OG_TYPE_TIMESTAMP_TZ_FAKE, OG_TYPE_TIMESTAMP, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_CLOB, OG_TYPE_TIMESTAMP_TZ, OG_TYPE_TIMESTAMP_TZ, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_CLOB, OG_TYPE_TIMESTAMP_LTZ, OG_TYPE_TIMESTAMP_LTZ, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_CLOB, OG_TYPE_BOOLEAN, OG_TYPE_BOOLEAN, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_CLOB, OG_TYPE_INTERVAL_YM, OG_TYPE_INTERVAL_YM, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_CLOB, OG_TYPE_INTERVAL_DS, OG_TYPE_INTERVAL_DS, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_CLOB, OG_TYPE_CLOB, OG_TYPE_STRING, OG_TRUE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_CLOB, OG_TYPE_IMAGE, OG_TYPE_STRING, OG_FALSE, OG_TRUE),

    __CMP_TYPE_DEF(OG_TYPE_IMAGE, OG_TYPE_UINT32, OG_TYPE_NUMBER, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_IMAGE, OG_TYPE_INTEGER, OG_TYPE_NUMBER, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_IMAGE, OG_TYPE_BIGINT, OG_TYPE_NUMBER, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_IMAGE, OG_TYPE_REAL, OG_TYPE_NUMBER, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_IMAGE, OG_TYPE_NUMBER, OG_TYPE_NUMBER, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_IMAGE, OG_TYPE_NUMBER2, OG_TYPE_NUMBER2, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_IMAGE, OG_TYPE_DECIMAL, OG_TYPE_NUMBER, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_IMAGE, OG_TYPE_CHAR, OG_TYPE_STRING, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_IMAGE, OG_TYPE_VARCHAR, OG_TYPE_STRING, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_IMAGE, OG_TYPE_STRING, OG_TYPE_STRING, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_IMAGE, OG_TYPE_BINARY, OG_TYPE_BINARY, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_IMAGE, OG_TYPE_VARBINARY, OG_TYPE_VARBINARY, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_IMAGE, OG_TYPE_RAW, OG_TYPE_RAW, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_IMAGE, OG_TYPE_DATE, OG_TYPE_DATE, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_IMAGE, OG_TYPE_TIMESTAMP, OG_TYPE_TIMESTAMP, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_IMAGE, OG_TYPE_TIMESTAMP_TZ_FAKE, OG_TYPE_TIMESTAMP, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_IMAGE, OG_TYPE_TIMESTAMP_TZ, OG_TYPE_TIMESTAMP_TZ, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_IMAGE, OG_TYPE_TIMESTAMP_LTZ, OG_TYPE_TIMESTAMP_LTZ, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_IMAGE, OG_TYPE_BOOLEAN, OG_TYPE_BOOLEAN, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_IMAGE, OG_TYPE_INTERVAL_YM, OG_TYPE_INTERVAL_YM, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_IMAGE, OG_TYPE_INTERVAL_DS, OG_TYPE_INTERVAL_DS, OG_FALSE, OG_FALSE),
    __CMP_TYPE_DEF(OG_TYPE_IMAGE, OG_TYPE_CLOB, OG_TYPE_STRING, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_IMAGE, OG_TYPE_IMAGE, OG_TYPE_STRING, OG_TRUE, OG_TRUE),

    __CMP_TYPE_DEF(OG_TYPE_VARBINARY, OG_TYPE_CHAR, OG_TYPE_VARBINARY, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_VARBINARY, OG_TYPE_VARCHAR, OG_TYPE_VARBINARY, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_VARBINARY, OG_TYPE_STRING, OG_TYPE_VARBINARY, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_VARBINARY, OG_TYPE_BINARY, OG_TYPE_VARBINARY, OG_TRUE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_VARBINARY, OG_TYPE_VARBINARY, OG_TYPE_VARBINARY, OG_TRUE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_VARBINARY, OG_TYPE_RAW, OG_TYPE_VARBINARY, OG_FALSE, OG_TRUE),

    __CMP_TYPE_DEF(OG_TYPE_DATE, OG_TYPE_CHAR, OG_TYPE_DATE, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_DATE, OG_TYPE_VARCHAR, OG_TYPE_DATE, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_DATE, OG_TYPE_STRING, OG_TYPE_DATE, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_DATE, OG_TYPE_DATE, OG_TYPE_DATE, OG_TRUE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_DATE, OG_TYPE_TIMESTAMP, OG_TYPE_TIMESTAMP, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_DATE, OG_TYPE_TIMESTAMP_TZ_FAKE, OG_TYPE_TIMESTAMP, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_DATE, OG_TYPE_TIMESTAMP_TZ, OG_TYPE_TIMESTAMP_TZ, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_DATE, OG_TYPE_TIMESTAMP_LTZ, OG_TYPE_TIMESTAMP_LTZ, OG_FALSE, OG_TRUE),

    __CMP_TYPE_DEF(OG_TYPE_TIMESTAMP, OG_TYPE_CHAR, OG_TYPE_TIMESTAMP, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_TIMESTAMP, OG_TYPE_VARCHAR, OG_TYPE_TIMESTAMP, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_TIMESTAMP, OG_TYPE_STRING, OG_TYPE_TIMESTAMP, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_TIMESTAMP, OG_TYPE_DATE, OG_TYPE_TIMESTAMP, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_TIMESTAMP, OG_TYPE_TIMESTAMP, OG_TYPE_TIMESTAMP, OG_TRUE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_TIMESTAMP, OG_TYPE_TIMESTAMP_TZ_FAKE, OG_TYPE_TIMESTAMP, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_TIMESTAMP, OG_TYPE_TIMESTAMP_TZ, OG_TYPE_TIMESTAMP_TZ, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_TIMESTAMP, OG_TYPE_TIMESTAMP_LTZ, OG_TYPE_TIMESTAMP_LTZ, OG_FALSE, OG_TRUE),

    __CMP_TYPE_DEF(OG_TYPE_TIMESTAMP_TZ_FAKE, OG_TYPE_CHAR, OG_TYPE_TIMESTAMP, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_TIMESTAMP_TZ_FAKE, OG_TYPE_VARCHAR, OG_TYPE_TIMESTAMP, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_TIMESTAMP_TZ_FAKE, OG_TYPE_STRING, OG_TYPE_TIMESTAMP, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_TIMESTAMP_TZ_FAKE, OG_TYPE_DATE, OG_TYPE_TIMESTAMP, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_TIMESTAMP_TZ_FAKE, OG_TYPE_TIMESTAMP, OG_TYPE_TIMESTAMP, OG_TRUE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_TIMESTAMP_TZ_FAKE, OG_TYPE_TIMESTAMP_TZ_FAKE, OG_TYPE_TIMESTAMP, OG_TRUE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_TIMESTAMP_TZ_FAKE, OG_TYPE_TIMESTAMP_TZ, OG_TYPE_TIMESTAMP_TZ, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_TIMESTAMP_TZ_FAKE, OG_TYPE_TIMESTAMP_LTZ, OG_TYPE_TIMESTAMP_LTZ, OG_FALSE, OG_TRUE),

    __CMP_TYPE_DEF(OG_TYPE_TIMESTAMP_TZ, OG_TYPE_CHAR, OG_TYPE_TIMESTAMP_TZ, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_TIMESTAMP_TZ, OG_TYPE_VARCHAR, OG_TYPE_TIMESTAMP_TZ, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_TIMESTAMP_TZ, OG_TYPE_STRING, OG_TYPE_TIMESTAMP_TZ, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_TIMESTAMP_TZ, OG_TYPE_DATE, OG_TYPE_TIMESTAMP_TZ, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_TIMESTAMP_TZ, OG_TYPE_TIMESTAMP, OG_TYPE_TIMESTAMP_TZ, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_TIMESTAMP_TZ, OG_TYPE_TIMESTAMP_TZ_FAKE, OG_TYPE_TIMESTAMP_TZ, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_TIMESTAMP_TZ, OG_TYPE_TIMESTAMP_TZ, OG_TYPE_TIMESTAMP_TZ, OG_TRUE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_TIMESTAMP_TZ, OG_TYPE_TIMESTAMP_LTZ, OG_TYPE_TIMESTAMP_TZ, OG_FALSE, OG_TRUE),

    __CMP_TYPE_DEF(OG_TYPE_TIMESTAMP_LTZ, OG_TYPE_CHAR, OG_TYPE_TIMESTAMP_LTZ, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_TIMESTAMP_LTZ, OG_TYPE_VARCHAR, OG_TYPE_TIMESTAMP_LTZ, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_TIMESTAMP_LTZ, OG_TYPE_STRING, OG_TYPE_TIMESTAMP_LTZ, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_TIMESTAMP_LTZ, OG_TYPE_DATE, OG_TYPE_TIMESTAMP_LTZ, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_TIMESTAMP_LTZ, OG_TYPE_TIMESTAMP, OG_TYPE_TIMESTAMP_LTZ, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_TIMESTAMP_LTZ, OG_TYPE_TIMESTAMP_TZ_FAKE, OG_TYPE_TIMESTAMP_LTZ, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_TIMESTAMP_LTZ, OG_TYPE_TIMESTAMP_TZ, OG_TYPE_TIMESTAMP_TZ, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_TIMESTAMP_LTZ, OG_TYPE_TIMESTAMP_LTZ, OG_TYPE_TIMESTAMP_LTZ, OG_TRUE, OG_TRUE),

    __CMP_TYPE_DEF(OG_TYPE_INTERVAL_YM, OG_TYPE_CHAR, OG_TYPE_INTERVAL_YM, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_INTERVAL_YM, OG_TYPE_VARCHAR, OG_TYPE_INTERVAL_YM, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_INTERVAL_YM, OG_TYPE_STRING, OG_TYPE_INTERVAL_YM, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_INTERVAL_YM, OG_TYPE_INTERVAL_YM, OG_TYPE_INTERVAL_YM, OG_TRUE, OG_TRUE),

    __CMP_TYPE_DEF(OG_TYPE_INTERVAL_DS, OG_TYPE_CHAR, OG_TYPE_INTERVAL_DS, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_INTERVAL_DS, OG_TYPE_VARCHAR, OG_TYPE_INTERVAL_DS, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_INTERVAL_DS, OG_TYPE_STRING, OG_TYPE_INTERVAL_DS, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_INTERVAL_DS, OG_TYPE_INTERVAL_DS, OG_TYPE_INTERVAL_DS, OG_TRUE, OG_TRUE),

    __CMP_TYPE_DEF(OG_TYPE_ARRAY, OG_TYPE_STRING, OG_TYPE_ARRAY, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_ARRAY, OG_TYPE_CHAR, OG_TYPE_ARRAY, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_ARRAY, OG_TYPE_VARCHAR, OG_TYPE_ARRAY, OG_FALSE, OG_TRUE),
    __CMP_TYPE_DEF(OG_TYPE_ARRAY, OG_TYPE_ARRAY, OG_TYPE_ARRAY, OG_TRUE, OG_TRUE),
};   // end g_cmp_rules

status_t var_like(variant_t *left, variant_t *right, bool32 *result, bool32 has_escape, char escape,
    charset_type_t type)
{
    text_t *l_text = NULL;
    text_t *r_text = NULL;

    l_text = VALUE_PTR(text_t, left);
    r_text = VALUE_PTR(text_t, right);

    if (has_escape) {
        int32 cmp_ret = 0;
        OG_RETURN_IFERR(CM_CHARSET_FUNC(type).escape_like(l_text->str, l_text->str + l_text->len,
            r_text->str, r_text->str + r_text->len, escape, &cmp_ret));
        *result = (cmp_ret == 0);
        return OG_SUCCESS;
    }
    *result = CM_CHARSET_FUNC(type).like(l_text, r_text);
    return OG_SUCCESS;
}

static status_t var_compare_diff_type(const nlsparams_t *nls,
    variant_t *left, variant_t *right, int32 *result)
{
    char       buf[OG_STRING_BUFFER_SIZE];
    text_buf_t convert_buf;
    variant_t l_var;
    variant_t r_var;

    og_type_t  cmp_type = get_cmp_datatype(left->type, right->type);
    if (cmp_type == INVALID_CMP_DATATYPE) {
        OG_SET_ERROR_MISMATCH(left->type, right->type);
        return OG_ERROR;
    }

    CM_INIT_TEXTBUF(&convert_buf, OG_STRING_BUFFER_SIZE, buf);
    var_copy(left, &l_var);
    var_copy(right, &r_var);

    // !!!only one variant need use converting buffer
    OG_RETURN_IFERR(var_convert(nls, &l_var, cmp_type, &convert_buf));
    OG_RETURN_IFERR(var_convert(nls, &r_var, cmp_type, &convert_buf));

    return var_compare_same_type(&l_var, &r_var, result);
}

status_t var_compare(const nlsparams_t *nls, variant_t *left, variant_t *right, int32 *result)
{
    if (left->is_null) {
        *result = 1;
        return OG_SUCCESS;
    } else if (right->is_null) {
        *result = -1;
        return OG_SUCCESS;
    }
    
    if (SECUREC_UNLIKELY(OG_IS_UNKNOWN_TYPE(left->type) || OG_IS_UNKNOWN_TYPE(right->type))) {
        OG_THROW_ERROR(ERR_INVALID_DATA_TYPE, "comparision");
        return OG_ERROR;
    }

    if (left->type == right->type || get_cmp_rule(left->type, right->type)->same_type) {
        return var_compare_same_type(left, right, result);
    }

    return var_compare_diff_type(nls, left, right, result);
}

bool32 var_const_equal(const variant_t *v1, const variant_t *v2)
{
    if (v1->type != v2->type || v1->is_null != v2->is_null) {
        return OG_FALSE;
    } else if (v1->is_null == OG_TRUE && v2->is_null == OG_TRUE) {
        return OG_TRUE;
    }

    switch (v1->type) {
        case OG_TYPE_UINT32:
        case OG_TYPE_INTEGER:
        case OG_TYPE_INTERVAL_YM:
            return (v1->v_int == v2->v_int);

        case OG_TYPE_BIGINT:
        case OG_TYPE_INTERVAL_DS:
            return (v1->v_bigint == v2->v_bigint);

        case OG_TYPE_REAL:
            return (fabs(v1->v_real - v2->v_real) < OG_REAL_PRECISION);

        case OG_TYPE_NUMBER:
        case OG_TYPE_DECIMAL:
        case OG_TYPE_NUMBER2:
            return (cm_dec_cmp(&v1->v_dec, &v2->v_dec) == 0);

        case OG_TYPE_DATE:
        case OG_TYPE_TIMESTAMP_TZ_FAKE:
        case OG_TYPE_TIMESTAMP_LTZ:
        case OG_TYPE_INTERVAL:
            return (v1->v_date == v2->v_date);

        case OG_TYPE_TIMESTAMP_TZ:
            return (cm_tstz_cmp(VALUE_PTR(timestamp_tz_t, v1), VALUE_PTR(timestamp_tz_t, v2)) == 0);

        case OG_TYPE_TIMESTAMP:
            return (v1->v_tstamp == v2->v_tstamp);

        case OG_TYPE_CHAR:
        case OG_TYPE_VARCHAR:
        case OG_TYPE_STRING:
            return cm_text_equal(&v1->v_text, &v2->v_text);

        case OG_TYPE_BOOLEAN:
            return (v1->v_bool == v2->v_bool);

        case OG_TYPE_TYPMODE:
            return (memcmp(&v1->v_type, &v2->v_type, sizeof(typmode_t)) == 0);

        case OG_TYPE_ITVL_UNIT:
            return (v1->v_itvl_unit_id == v2->v_itvl_unit_id);

        default:
            return OG_FALSE;
    }
}

bool32 var_seq_equal(const var_seq_t *v1, const var_seq_t *v2)
{
    if (cm_text_equal_ins(&v1->user, &v2->user) && cm_text_equal(&v1->name, &v2->name) && v1->mode == v2->mode) {
        return OG_TRUE;
    }
    return OG_FALSE;
}
