CREATE TABLE ENGINES
(
  ENGINE varchar(64) NOT NULL DEFAULT '',
  SUPPORT varchar(8) NOT NULL DEFAULT '',
  COMMENT varchar(80) NOT NULL DEFAULT '',
  TRANSACTIONS varchar(3) DEFAULT NULL,
  XA varchar(3) DEFAULT NULL,
  SAVEPOINTS varchar(3) DEFAULT NULL
) SYSTEM 1047 TABLESPACE SYSAUX
/

ALTER SYSTEM LOAD DICTIONARY FOR ENGINES
/

