CREATE OR REPLACE PACKAGE UTL_RAW AS
  FUNCTION cast_to_raw(c IN VARCHAR2) RETURN RAW;
END UTL_RAW;
/

CREATE OR REPLACE PACKAGE BODY UTL_RAW AS
  FUNCTION cast_to_raw(c IN VARCHAR2) RETURN RAW IS
  BEGIN
        RETURN HEXTORAW(RAWTOHEX(c));
  END cast_to_raw;
END UTL_RAW;
/

GRANT EXECUTE ON sys.UTL_RAW TO PUBLIC;
CREATE PUBLIC SYNONYM UTL_RAW FOR sys.UTL_RAW;
