CREATE TABLE PG_ENUM
(
  oid int DEFAULT NULL,
  enumtypid int DEFAULT NULL,
  enumsortorder int DEFAULT NULL,
  enumlabel varchar(256) DEFAULT NULL
) SYSTEM 1048 TABLESPACE SYSAUX
/

ALTER SYSTEM LOAD DICTIONARY FOR PG_ENUM
/

